version: 2

sources:
  - name: reference
    database: stewart-bryson-423512
    schema: dl_source
    loader: seed

    tables:
      - name: status_type
      - name: industry
      - name: date
      - name: tax_rate
      - name: trade_type