version: 2

sources:
  - name: brokerage
    database: stewart-bryson-423512
    schema: dl_source
    loader: seed

    tables:
      - name: daily_market
      - name: watch_history
      - name: trade
      - name: trade_history
      - name: holding_history
      - name: cash_transaction
      
